version: '3.8'

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    entrypoint: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru --save ""
    restart: unless-stopped

  wp:
    build: build
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    hostname: ${SITE_URL}
    depends_on:
      - db
      - redis
    volumes:
      - ${WP_CONTENT}:/var/www/html/wp-content
      - ./wordpress:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
    expose:
      - 80
    depends_on:
      - wp
    networks:
      - reverse_proxy
      - default
    restart: unless-stopped

  wpcli:
    depends_on:
      - db
      - wp
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    entrypoint: wp
    command: "--info"
    volumes:
      - ./wordpress:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
      - ./w3t-config.json:/var/www/w3t-config.json
    working_dir: /var/www/html

  mail:
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=${SITE_URL}
      - OPENDKIM_DOMAINS=${SITE_URL}
    volumes:
      - ./dkim:/etc/opendkim/keys/
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db
  #   environment:
  #     PMA_ARBITRARY: 1
  #   restart: unless-stopped
  #   ports:
  #     - 8081:80

networks:
  reverse_proxy:
    external: true
    name: main
